<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="MIT01524" name="com.paymentgateway.uat.tpp.testcases.RegressionSalesDB" tests="6" failures="1" timestamp="29 Apr 2019 06:19:49 GMT" time="737.530" errors="0">
  <testcase name="testRefundPaymentFromSalesDB" time="43.002" classname="com.paymentgateway.uat.tpp.testcases.RegressionSalesDB"/>
  <testcase name="testDomainRegistration2WorkflowInConsoleAdmin" time="167.017" classname="com.paymentgateway.uat.tpp.testcases.RegressionSalesDB">
    <failure type="java.lang.AssertionError" message="update star rating expected [domain registration completed] but found [update star rating]">
      <![CDATA[java.lang.AssertionError: update star rating expected [domain registration completed] but found [update star rating]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at com.paymentgateway.uat.tpp.testcases.RegressionSalesDB.testDomainRegistration2WorkflowInConsoleAdmin(RegressionSalesDB.java:180)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- testDomainRegistration2WorkflowInConsoleAdmin -->
  <testcase name="testPaySingleInvoiceInConsoleAdmin" time="191.675" classname="com.paymentgateway.uat.tpp.testcases.RegressionSalesDB"/>
  <testcase name="testPayInvoiceUsingExistingCardFromSalesDB" time="36.812" classname="com.paymentgateway.uat.tpp.testcases.RegressionSalesDB"/>
  <testcase name="testCreateDomainAndMajorProductOrderInSalesDB" time="88.372" classname="com.paymentgateway.uat.tpp.testcases.RegressionSalesDB"/>
  <testcase name="testProductSetup2WorkflowInConsoleAdmin" time="210.652" classname="com.paymentgateway.uat.tpp.testcases.RegressionSalesDB"/>
</testsuite> <!-- com.paymentgateway.uat.tpp.testcases.RegressionSalesDB -->
